# Generated by Django 4.2.5 on 2023-12-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0003_rename_name_question_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='username',
            field=models.TextField(),
        ),
    ]
