# Generated by Django 4.2.5 on 2023-12-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0006_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='requests',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.CharField(choices=[('Single', 'Single'), ('Standart', 'Standart'), ('Premium', 'Premium')], max_length=50),
        ),
    ]
