# Generated by Django 4.2.5 on 2023-12-07 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0007_alter_booking_phone_alter_booking_requests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='datein',
            new_name='date_in',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='dateout',
            new_name='date_out',
        ),
    ]
