# Generated by Django 4.2.5 on 2023-12-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0009_question_is_answered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_answered',
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('Отвечено', 'Отвечено'), ('Не отвечено', 'Не отвечено')], default='Не отвечено'),
        ),
    ]
