# Generated by Django 4.2.5 on 2023-12-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0010_remove_question_is_answered_question_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='full_name',
        ),
    ]
