# Generated by Django 4.2.5 on 2023-12-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0011_rename_name_booking_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.CharField(choices=[('Single', 'Single'), ('Standart', 'Standart'), ('StandartMarry', 'Standart (для молодожёнов)'), ('Premium', 'Premium')], max_length=50),
        ),
    ]
