# Generated by Django 4.2.5 on 2023-12-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0012_alter_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.CharField(choices=[('Single', 'Single'), ('Standart', 'Standart'), ('StandartMarry', 'Standart для молодожёнов'), ('Premium', 'Premium')], max_length=50),
        ),
    ]
