# Generated by Django 4.2.5 on 2023-12-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0013_alter_booking_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='username',
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('Отвечено', 'Отвечено'), ('Не отвечено', 'Не отвечено')], default='Не отвечено', max_length=300),
        ),
    ]
