# Generated by Django 4.2.5 on 2023-12-16 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0014_remove_question_username_question_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.SlugField(default=89998887766, validators=[django.core.validators.RegexValidator(regex='(?:\\+7|8)\\d{10}')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='requests',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.CharField(),
        ),
    ]
