# Generated by Django 4.2.5 on 2023-12-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0015_alter_booking_full_name_alter_booking_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='requests',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.CharField(choices=[('Single', 'Single'), ('Standart', 'Standart'), ('Premium', 'Premium')]),
        ),
    ]
