# Generated by Django 4.2.5 on 2024-01-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0016_alter_booking_requests_alter_booking_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='full_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.SlugField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.SlugField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='booking',
            name='patronymic',
            field=models.SlugField(default='', max_length=70),
        ),
    ]
