# Generated by Django 4.2.5 on 2024-01-02 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0017_remove_booking_full_name_booking_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='', max_length=70, validators=[django.core.validators.RegexValidator(regex='\\w+')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default='', max_length=70, validators=[django.core.validators.RegexValidator(regex='\\w+')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='patronymic',
            field=models.CharField(default='', max_length=70, validators=[django.core.validators.RegexValidator(regex='\\w+')]),
        ),
    ]
