# Generated by Django 4.2.5 on 2024-01-03 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0022_alter_booking_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.SlugField(default='', validators=[django.core.validators.RegexValidator(regex='(?:\\+7|8)\\d{10}')]),
        ),
    ]
