# Generated by Django 4.2.5 on 2024-01-03 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0023_alter_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='', validators=[django.core.validators.RegexValidator(regex='(?:\\+7|8)\\d{10}')]),
        ),
    ]
