# Generated by Django 4.2.5 on 2024-01-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0025_remove_booking_first_name_remove_booking_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default=''),
        ),
    ]
