# Generated by Django 4.2.5 on 2024-01-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0028_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='requests',
            field=models.CharField(default='', max_length=50),
        ),
    ]
