# Generated by Django 4.2.5 on 2024-01-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0029_alter_booking_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='requests',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
