# Generated by Django 4.2.5 on 2023-12-16 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='category',
            field=models.CharField(choices=[('Single', 'Single'), ('Standart', 'Standart'), ('Standart_merry', 'Standart (для молодожёнов)'), ('Premium', 'Premium')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='multi',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
