# Generated by Django 4.2.5 on 2023-12-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_roomcategory_category_roomcategory_multi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
