# Generated by Django 4.2.5 on 2023-12-16 19:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_roomcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='room',
            name='room_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff.roomcategory'),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='category',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
