# Generated by Django 4.2.5 on 2023-12-16 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_rename_room_category_room_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcategory',
            name='multi',
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='staff.roomcategory'),
        ),
    ]
