# Generated by Django 4.2.5 on 2023-12-16 20:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_remove_roomcategory_multi_alter_room_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomAvailability',
        ),
        migrations.AddField(
            model_name='guest',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='date_in',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='date_out',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AddField(
            model_name='guest',
            name='full_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='guest',
            name='passport',
            field=models.SlugField(default='123456-0000', validators=[django.core.validators.RegexValidator(regex='\\d{6}-\\d{4}')]),
        ),
        migrations.AddField(
            model_name='guest',
            name='phone',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.RegexValidator(regex='(?:\\+7|8)\\d{10}')]),
        ),
        migrations.AddField(
            model_name='guest',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='staff.room', unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='availability',
            field=models.SlugField(choices=[('Occupied', 'Занято'), ('Free', 'Свободно')], default='Свободно'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
