# Generated by Django 4.2.5 on 2023-12-16 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_delete_roomavailability_guest_birth_guest_date_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.SlugField(null=True, validators=[django.core.validators.RegexValidator(regex='(?:\\+7|8)\\d{10}')]),
        ),
    ]
