# Generated by Django 4.2.5 on 2024-01-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_alter_guest_full_name_alter_guest_room_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.SlugField(choices=[('Занято', 'Занято'), ('Свободно', 'Свободно')], default='Свободно', editable=False),
        ),
    ]
