# Generated by Django 4.2.5 on 2024-01-05 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_alter_room_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='guest',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='staff.guest'),
        ),
    ]
