# Generated by Django 4.2.5 on 2024-01-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_alter_guest_passport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='number',
            new_name='room',
        ),
    ]
