# Generated by Django 4.2.5 on 2024-01-07 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_rename_number_room_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room',
            field=models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
