# Generated by Django 4.2.5 on 2024-01-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_alter_room_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.SlugField(choices=[('Занято', 'Занято'), ('Свободно', 'Свободно')], default='Свободно'),
        ),
    ]
