# Generated by Django 4.2.5 on 2024-01-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_alter_room_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.CharField(choices=[('Занято', 'Занято'), ('Свободно', 'Свободно')], default='Свободно'),
        ),
    ]
